language: python
python: '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover --start-directory ./tests/ --pattern '*_test.py' --verbose
after_success:
- ".travis/push.sh"
deploy:
  provider: pypi
  user: thomascountz
  password:
    secure: jK78pc3HJcj9Hi7Prsn0SSbBwffo3xuRispeuTV37ibtGgwp1u0/9AIZ58qJmNxZSX22UY+gB8yDL06dig2Csxz035CxXtdzXh4foSDUHp+QE/kMI0vryEOfBES/VOYlaZ+DdayOlbWG5pzPKya2AIAuAM3Lf9b2twilFfXF+r87J52U4KyYmIO2HtHQbUCS7yH/lqe88C6A2CRm4fLIlXaawOYB9/+k4Um+nCUXeRpnyZfD7hctMW/h8OU6K8qFOvicJp0e0c0O/TkPAaeOnerjDUwa/sfGt3XiTMH9C9gRmKUOYKX40p5XEnXKUiJAjd6mHgDyGRzhGZkB36wZ3hfIFF6gG04mc8ehtz3NbCWDcZkD4xVmjHw3FT1aWJZKD+Yp69tlswcAz3glo8DkhhqEn+LIe2UPGPRrYzIGt9aX8V9ne1x78apo+OqUhlSaPMFRHCdLchGKExH4pFMKe61V4yF59hVfrpwQBSPgtu2ksyaAlDqR3vVXBBZNOlpACaDVU61ZLd4qF2X9RxdAt9aujs5tkhZaJ9KZAbwCGwNchrZtBkZr8SYnZcWEGTCR/ZXDG2OyROGhaeaR/NGJETDI9ymfYJ4Ro/000DcTJzLMsdn1Wg6i4R4a7RfPOEUEcq9tUmxyYAFYYmqKGJkGQDKDLv0EV4uzr3mcNS3H3EI=
  on:
    branch: pre-deploy
    tags: true
env:
  global:
    secure: uwr6x6yTnqWZDQ9QgT/uSNqlhQQClERMc0ME7ZEGU+tWw5RShpTt61Om6OF1yYI6pwsOrJ2uFCpDbHdshzd4Q0nTwZb1lHygX5HiGJ/2iJOtU533x2OXiJ5T/DaTmAjxKQRw+3GngjeFhWBNJ3uN/zesh1HdPx5q7PlxuVlrJMUuf2yg9BG5CcW+RMr/AleNX2zoozKzzpQNN94u7yfkh8Ay/0Z23JC5akRyD6qgWvQU6cNgrw1d0z0Fp90ycapdhqvsxZrRFLc4BM1SgZiH4zCcm8TtctwRWJCysHWa+SdJmjb4b76HcZT8U61xtreSclJcRcow0Jd2DDIqwBWqei2ZdDkvdEopN2JQBnHZBnUJ9X1EBptxkxeBlFWFiBwTNg46LhuFQ5cO+qApuP2k7qY0feVvmoeNf6PsBgvATA2+3YubjYGA3vNFVEn8fV1kWEowuhDrBNRVr9WRXPXR8aK0hzmohGUUNXooajLzD5RrJyqcjwuDe59GPgL+TPt0OcFkOIN1KmVljFvxzQxVmDVf/l3yeNs2ISRM/hTFuNg1WRtkCp+d+ITzRfu/sTxpm1Bcm0JD/z+CnLtms3ELo4oQto1bzQeLpu+bosR6FerSkyJG1SRps0I910QbvUC8LKcSEpd0vrWa8qXnBztQvYA/2fcu2AmxYnagM+sxUSo=
